

function classic_round(value)
	if value % 1 >= 0.5 then
		return math.ceil(value)
	else
		return math.floor(value)
	end
end

function clamp_in_range(min_value, current_value, max_value)
	if current_value > max_value then
		current_value = max_value
	end
	
	if current_value < min_value then
		current_value = min_value
	end
	
	return current_value
end

function scaled_random(min_value, max_value, multiplier_coeff)
    return math.random(min_value, max_value) * multiplier_coeff
end

function safe_divide(first_vale, second_value)
	if not first_vale or first_vale == 0 then
		return 0
	end
	
	if not second_value or second_value == 0 then
		return 0
	end
	
	return first_vale / second_value
end